### PR TITLE
Update to Angular 15/16 compatibility

### PR DESCRIPTION
**Pull request by pdeffendol**

### CODE REVIEW

**Comment by pdeffendol** [comment]
🛑 The "comparison" column header option for the table component has a button that pops up a panel for filtering information.  However, this only inserts and removes the panel right into the table header.  The Material 15+ table component hides overflow on table headers, so the panel is not completely visible.  It probably needs to be converted to a CDK overlay.

**Review by carsonsorenson — COMMENTED** [review]
Looks good. Were you able to get the link working to verify the styles looked ok?

**Comment by pdeffendol** [comment]
> Looks good. Were you able to get the link working to verify the styles looked ok?

I am in the process of converting the comparison filter to use CDK Overlay and that should be everything.  I'm comparing to the Dev deploy of Licensing for visual differences.

**Comment by pdeffendol** [comment]
@carsonsorenson the comparison filter has been updated

**Review by carsonsorenson — APPROVED** [review]

**Pull request merged**
